var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { styled } from "styled-components";
var InputText = styled.input(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: block;\n  width: 100%;\n  padding: 0.375rem 0.75rem;\n  font-size: 1rem;\n  font-weight: 400;\n  line-height: 1.5;\n  color: #000000;\n  -webkit-appearance: none;\n  -moz-appearance: none;\n  appearance: none;\n  background-color: #ffffff;\n  background-clip: padding-box;\n  border: 1px solid #dee2e6;\n  border-radius: 0.375rem;\n  transition:\n    border-color 0.15s ease-in-out,\n    box-shadow 0.15s ease-in-out;\n\n  &:focus {\n    color: #212529;\n    background-color: #ffffff;\n    border-color: #86b7fe;\n    outline: 0;\n    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);\n  }\n"], ["\n  display: block;\n  width: 100%;\n  padding: 0.375rem 0.75rem;\n  font-size: 1rem;\n  font-weight: 400;\n  line-height: 1.5;\n  color: #000000;\n  -webkit-appearance: none;\n  -moz-appearance: none;\n  appearance: none;\n  background-color: #ffffff;\n  background-clip: padding-box;\n  border: 1px solid #dee2e6;\n  border-radius: 0.375rem;\n  transition:\n    border-color 0.15s ease-in-out,\n    box-shadow 0.15s ease-in-out;\n\n  &:focus {\n    color: #212529;\n    background-color: #ffffff;\n    border-color: #86b7fe;\n    outline: 0;\n    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);\n  }\n"])));
var InputRadio = styled.input(templateObject_2 || (templateObject_2 = __makeTemplateObject([""], [""])));
var Label = styled.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin-bottom: 0.5rem;\n  display: block;\n"], ["\n  margin-bottom: 0.5rem;\n  display: block;\n"])));
var ErrorMessage = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  color: red;\n"], ["\n  color: red;\n"])));
var Form = styled.form(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  margin: 0 auto;\n  height: 100%;\n  display: flex;\n  flex-flow: column;\n  align-items: center;\n  justify-content: center;\n  flex: 1 1 auto;\n"], ["\n  margin: 0 auto;\n  height: 100%;\n  display: flex;\n  flex-flow: column;\n  align-items: center;\n  justify-content: center;\n  flex: 1 1 auto;\n"])));
var Button = styled.button(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  padding: 6px 12px;\n  border: 1px solid #0d6efd;\n  background-color: #0d6efd;\n  color: #ffffff;\n  cursor: pointer;\n  border-radius: 5px;\n  transition:\n    color 0.15s ease-in-out,\n    background-color 0.15s ease-in-out,\n    border-color 0.15s ease-in-out,\n    box-shadow 0.15s ease-in-out;\n  &:hover {\n    background-color: #0a58ca;\n    border-color: #0a58ca;\n    color: #ffffff;\n  }\n"], ["\n  padding: 6px 12px;\n  border: 1px solid #0d6efd;\n  background-color: #0d6efd;\n  color: #ffffff;\n  cursor: pointer;\n  border-radius: 5px;\n  transition:\n    color 0.15s ease-in-out,\n    background-color 0.15s ease-in-out,\n    border-color 0.15s ease-in-out,\n    box-shadow 0.15s ease-in-out;\n  &:hover {\n    background-color: #0a58ca;\n    border-color: #0a58ca;\n    color: #ffffff;\n  }\n"])));
var WrapperFormContent = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  gap: 10px;\n"], ["\n  display: flex;\n  align-items: center;\n  gap: 10px;\n"])));
export { InputText, Label, ErrorMessage, Form, Button, InputRadio, WrapperFormContent, };
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
